version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: myapp_mysql
    environment:
      MYSQL_DATABASE: nest-project
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: nest-project
      MYSQL_PASSWORD: nest-project
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: myapp
    environment:
      DATABASE_URL: mysql://nest-project:nest-project@db:3306/nest-project
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
