version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: myapp_mysql
    environment:
      MYSQL_DATABASE: nest-project
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: nest-project
      MYSQL_PASSWORD: nest-project
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
